version: "2"
run:
  go: "1.18"
linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - errcheck
    - funlen
    - goconst
    - gocyclo
    - govet
    - ineffassign
    - lll
    - misspell
    - nestif
    - nilnil
    - revive
    - staticcheck
    - tagliatelle
    - unconvert
    - unparam
    - unused
  settings:
    lll:
      line-length: 140
    misspell:
      locale: US
    tagliatelle:
      case:
        rules:
          json: snake
          whatever: snake
          xml: snake
          yaml: snake
        use-field-name: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - staticcheck
        text: 'SA5008: unknown JSON option ("optional"|"default=|"range=|"options=)'
      - path: (.+)\.go$
        text: .IDs
    paths:
      - _test.go
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - _test.go
      - third_party$
      - builtin$
      - examples$
